export const SET_USER_AUTENTICATED = 'SET_USER_AUTENTICATED';
export const SET_USER_UNAUTENTICATED = 'SET_USER_UNAUTENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
